export const SELECTED_NAME = 'SELECTED_IMAGE';
export const JSONPLACEHOLDER_NAMES_SUCCESS = 'JSONPLACEHOLDER_NAMES_SUCCESS';
export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST';
export const SEARCH_MEDIA_SUCCESS = 'SEARCH_MEDIA_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';